# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20160208_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issues_duedate_warning',
            field=models.PositiveIntegerField(default=5, verbose_name='issues due date warning'),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks_duedate_warning',
            field=models.PositiveIntegerField(default=5, verbose_name='tasks due date warning'),
        ),
        migrations.AddField(
            model_name='project',
            name='userstories_duedate_warning',
            field=models.PositiveIntegerField(default=5, verbose_name='user stories due date warning'),
        ),
    ]
